repos:
  - repo: local
    hooks:
      - id: unittest-check
        name: Run Unittest
        entry: python -m unittest discover -s tests
        language: system
        pass_filenames: false
        types: [python]